# Homeworks

* For the following interpretations of Matrix-vector and Matrix-Matrix product write the corresponding python code using for loops, as exemplified during the lecture.
* You need to complete the example partial codes provided below
* Two relevant examples from class follow


### Example matrix-vector products
![](assets/Lecture_5_text-7f3aa5f7.png)
![](assets/Lecture_5_text-95ec9688.png)
![](assets/Lecture_5_text-cf1e838d.png)

In [1]:
import numpy as np
# example writing A by rows
A = np.random.random((3,4))
x = np.random.random((4,))
y = np.zeros( A.shape[0])

for n in range(A.shape[0]):
        y[n] = A[n,:]@x
            
print(np.allclose(y,A@x)) # check if vectors are the same          

True


In [3]:
# example writing A by columns
y = np.zeros( A.shape[0])

for n in range(A.shape[1]):
        y += A[:,n]*x[n]
            
print(np.allclose(y,A@x))  # check if vectors are the same          

True


### Exercise 1:  vector-matrix product, with matrix interpreted as column vectors  (2 pts)

![](assets/Lecture_5_text-fd5b6364.png)

In [4]:
import numpy as np
# example writing A by columns
x = np.random.random((3,1))
A = np.random.random((3,4))
y = np.zeros((x.T.shape[0], A.shape[1]))

# ADD YOUR CODE HERE 

for i in range(A.shape[1]):
    #y[0,i] += x.T@A[:,i]
    y[0,i] += np.inner(x.T,A[:,i])

print(np.allclose(y,x.T@A))


True


### Exercise 2:  vector-matrix product, with matrix interpreted as row vectors  (2 pts)

![](assets/Lecture_5_text-3da1ef5b.png)

In [5]:
import numpy as np
# example writing A by rows
x = np.random.random((3,1))
A = np.random.random((3,4))
y = np.zeros((x.T.shape[0], A.shape[1]))

# ADD YOUR CODE HERE  

for i in range(A.shape[0]):
    y += x.T[0,i]*A[i,:]

print(np.allclose(y,x.T@A)) # check if vectors are the same          

True


### Exercise 3:  matrix-matrix product, with two matrices interpreted as row and column vectors  (2 pts)

# matrix-matrix products

we will look at the different ways to interpret the product C = AB, generalizing what seen above

* A rows, B columns
![](assets/Lecture_5_text-291584e5.png)

In [6]:
import numpy as np
# example writing A by rows
A = np.random.random((3,4))
B = np.random.random((4,5))
C = np.zeros((A.shape[0], B.shape[1]))
row, col = C.shape

## ADD YOUR CODE HERE
    
for i in range(row):
  for j in range(col):
    C[i,j] =  A[i,:]@B[:,j]   
       
print(np.allclose(C,A@B)) # check if vectors are the same          

True


### Exercise 4:  matrix-matrix product, with two matrices interpreted as column and row vectors  (2 pts)

* A columns, B rows
![](assets/Lecture_5_text-4da76187.png)
AB is equal to the sum, over all i, of the outer product of the i-th column of A and the i-th row of B. Difficult expression.

In [7]:
import numpy as np
# example writing A by rows
A = np.random.random((3,4))
B = np.random.random((4,5))
C = np.zeros((A.shape[0], B.shape[1]))


## ADD YOUR CODE HERE (beware this is tricky but highly educative!)
for i in range(A.shape[1]):
    C += np.outer(A[:,i],B[i,:])

print(np.allclose(C,A@B)) # check if vectors are the same          

True


### Exercise 5:  trace of a matrix  (1 pt)

*  implement the trace operation using one for loop
*  probe using python code the properties of traces

### trace of a matrix
![](assets/Lecture_5_text-1d8e4959.png)

In [8]:
import numpy as np
#implement the trace operation using one for loop
A = np.random.random((3,3))

### add your code here
trc = 0
if A.shape[0] == A.shape[1]:
    NumOfDiagElements = A.shape[0]

for i in range(NumOfDiagElements):
    trc += A[i,i]

print(np.allclose(trc,np.trace(A))) # check if vectors are the same          

True


### Properties of trace
![](assets/Lecture_5_text-13f536da.png)

In [9]:
# probe using python code the properties of traces
# Example property one
A = np.random.random((3,3))
print(np.allclose(np.trace(A),np.trace(A.T)))

# Example property two
B = np.random.random((3,3))
print(np.allclose(np.trace(A+B),np.trace(A) + np.trace(B)))


## add here your code for property 3
A = np.random.random((3,3))
t = 5

# trc(tA)
tA = t*A
trc_tA = 0
for i in range(tA.shape[0]):
    trc_tA += trc_tA + tA[i,i]
print(trc_tA)

# t_trc(A)
trc = 0
for i in range(A.shape[0]):
    trc += trc + A[i,i]
t_trcA = t*trc
print(t_trcA)

print(np.allclose(np.trace(t*A),t*np.trace(A)))



## add here your code for property 4
A = np.random.random((3,4))
B = np.random.random((4,3))

AB = A@B
trcAB = 0
for i in range(AB.shape[0]):
    trcAB = trcAB + AB[i,i]
print(trcAB)

BA = B@A
trcBA = 0
for i in range(BA.shape[0]):
    trcBA = trcBA + BA[i,i]
print(trcBA)

print(np.allclose(np.trace(B@A),np.trace(A@B)))



## add here your code for property 5
A = np.random.random((3,3))
B = np.random.random((3,4))
C = np.random.random((4,3))

ABC = A@B@C
trcABC = 0
for i in range(ABC.shape[0]):
    trcABC = trcABC + ABC[i,i]
print(trcABC)

BCA = B@C@A
trcBCA = 0
for i in range(BCA.shape[0]):
    trcBCA = trcBCA + BCA[i,i]
print(trcBCA)

CAB = C@A@B
trcCAB = 0
for i in range(CAB.shape[0]):
    trcCAB = trcCAB + CAB[i,i]
print(trcCAB)

print(np.allclose(np.trace(B@C@A),np.trace(A@B@C), np.trace(C@A@B)))

True
True
12.616397878270995
12.616397878270998
True
3.299513270857709
3.299513270857709
True
5.448219127903865
5.448219127903865
5.448219127903865
True


### Exercise 6:  Matrix-matrix multiplication with second matrix interpreted as column  (2 pts)

Set of matrix-vector products
![](assets/Lecture_5_text-1a3dac83.png)"

In [10]:
A = np.random.random((3,4))
B = np.random.random((4,5))
rows, cols = A.shape[0], B.shape[1]
C = np.zeros((rows, cols))

## ADD YOUR CODE HERE
for i in range(cols):
    C[:,i] = A[:,:]@B[:,i]
    print(C)
            
print(np.allclose(C,A@B))     

[[1.96249086 0.         0.         0.         0.        ]
 [1.63365472 0.         0.         0.         0.        ]
 [2.04272142 0.         0.         0.         0.        ]]
[[1.96249086 1.14857256 0.         0.         0.        ]
 [1.63365472 0.80672052 0.         0.         0.        ]
 [2.04272142 1.3122281  0.         0.         0.        ]]
[[1.96249086 1.14857256 1.21342386 0.         0.        ]
 [1.63365472 0.80672052 1.22356448 0.         0.        ]
 [2.04272142 1.3122281  1.75675992 0.         0.        ]]
[[1.96249086 1.14857256 1.21342386 0.96880221 0.        ]
 [1.63365472 0.80672052 1.22356448 1.24351124 0.        ]
 [2.04272142 1.3122281  1.75675992 0.99765671 0.        ]]
[[1.96249086 1.14857256 1.21342386 0.96880221 0.91177006]
 [1.63365472 0.80672052 1.22356448 1.24351124 0.76253209]
 [2.04272142 1.3122281  1.75675992 0.99765671 1.00472114]]
True


### Exercise 7:  Matrix-matrix multiplication with first matrix interpreted as rows  (2 pts)

![](assets/Lecture_5_text-5c8cebb4.png)

In [11]:
A = np.random.random((3,4))
B = np.random.random((4,5))
rows, cols = A.shape[0], B.shape[1]
C = np.zeros((rows, cols))

## ADD YOUR CODE HERE

for i in range(rows):
    C[i,:] = A[i,:]@B[:,:]
    print(C)
            
print(np.allclose(C,A@B))     

[[0.97575109 1.21770171 0.67108146 0.99431815 0.69129516]
 [0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.        ]]
[[0.97575109 1.21770171 0.67108146 0.99431815 0.69129516]
 [0.8487531  1.06707729 0.37756073 0.98547635 0.8053822 ]
 [0.         0.         0.         0.         0.        ]]
[[0.97575109 1.21770171 0.67108146 0.99431815 0.69129516]
 [0.8487531  1.06707729 0.37756073 0.98547635 0.8053822 ]
 [1.40059453 2.36662722 1.35817767 1.66963355 1.21694504]]
True
