In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

train_data = pd.read_csv("https://storage.googleapis.com/kaggle-competitions-data/kaggle/3136/train.csv?GoogleAccessId=web-data@kaggle-161607.iam.gserviceaccount.com&Expires=1571530351&Signature=E6%2FFs6iCoMjaz73DxuzsU5d7sYrul5Wk9qB1GVRFo6SlyOt5qjC0Wgc822EgXJiqAP8MaMkYzmzsry8uCBjf1CanasKzwafvqBPNT%2FFrq%2BfVpJIVrCjNcVZplJu6PNC2zfW6Yt4URbWJUFqq5IBWfJSPzTYyoUmS9XHdhGs0HKCfhdhHce2JXlqp44KwEwyytAP8XwpCYMmAuo8z6He%2Bmc6k2a%2BDb%2FfWjXTyo1LD%2Bd%2FyN%2B%2Buxaev8Dh8I8OKmUZ0GRTOtCrjmt%2F6HJfR%2BYWrAo%2F35lfON6b0c9Iq5MI58EuTiKdCYqch9%2BfgoTEiPkEy6pJUvjEPpG117uPJhIcbmw%3D%3D")
test_data = pd.read_csv("https://storage.googleapis.com/kaggle-competitions-data/kaggle/3136/test.csv?GoogleAccessId=web-data@kaggle-161607.iam.gserviceaccount.com&Expires=1571530316&Signature=DKwUQngipVrSmPCGLLRkzfCdmJ82DBC%2FUTGs8PqULJuKs%2BoO50R317jwRmGMiY%2FT2yMqFt%2FUMDc0grmts3pmaaKqybDYrYiBq9YkWYx7JyR6skigo9g81XowuyHQ8RtcXl4PyS%2FLDzZ0ee3CWW3zdDKPIvIITsqQYB%2F3cwJT0GB%2BZPqkQ7xI%2BmL8%2FzUkwdGr9kIRHNV9ut3Ffts8Oe7t7UpVw7PRlTVi9fnz4Jea7Obtkn91A8MwpoC5ohMy2IY5vOqSUM3owjmu9VoA7HQmsDgnqGM0J3JAz8oIR2DWjrK04BRRZfW%2FHYitk%2BVCDX1JVL%2BAFI8EOVIjSjLIEJt%2FPg%3D%3D")

In [2]:
# Ground truth data for tests later on to avoid having to resubmit to kaggle to see my score everytime
import os
import re
import warnings

ground_truth = pd.read_csv('/Users/williamstanford/machine-learning-BMME890/handson-ml/submission.csv')
gtruth_just_outcomes = ground_truth["Survived"]

In [3]:
train_data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [4]:
test_data.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [5]:
train_data["AgeBucket"] = train_data["Age"] // 5 * 5
train_data[["AgeBucket", "Survived"]].groupby(['AgeBucket']).mean()

Survived
AgeBucket          
0.0        0.675000
5.0        0.500000
10.0       0.437500
15.0       0.395349
20.0       0.342105
25.0       0.358491
30.0       0.421053
35.0       0.458333
40.0       0.375000
45.0       0.390244
50.0       0.437500
55.0       0.375000
60.0       0.400000
65.0       0.000000
70.0       0.000000
80.0       1.000000

In [6]:
# Added an age bucket to see if models more easily can latch onto discrete variables rather than continuous
# From book, adjusted bucket sizes

test_data["AgeBucket"] = train_data["Age"] // 5 * 5
train_data[["AgeBucket", "Survived"]].groupby(['AgeBucket']).mean()

Survived
AgeBucket          
0.0        0.675000
5.0        0.500000
10.0       0.437500
15.0       0.395349
20.0       0.342105
25.0       0.358491
30.0       0.421053
35.0       0.458333
40.0       0.375000
45.0       0.390244
50.0       0.437500
55.0       0.375000
60.0       0.400000
65.0       0.000000
70.0       0.000000
80.0       1.000000

In [7]:
train_data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  AgeBucket  
0      0         A/5 21171   7.2500   NaN        S       20.0  
1      0          PC 17599  71.2833   C85        C       35.0  
2      0  STON/O2. 3101282   7.9250   NaN        S       25.0  
3      0            113803  53.1000  C123        S       35.0  
4      0            373450   8.0500   NaN        S       35.0

In [8]:
# Preprocessing pipleline from book 

from sklearn.base import BaseEstimator, TransformerMixin

class DataFrameSelector(BaseEstimator, TransformerMixin):
    def __init__(self, attribute_names):
        self.attribute_names = attribute_names
    def fit(self, X, y=None):
        return self
    def transform(self, X):
        return X[self.attribute_names]

In [9]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import Imputer as SimpleImputer

num_pipeline = Pipeline([
        ("select_numeric", DataFrameSelector(["Age", "SibSp", "Parch", "Fare"])),
        ("imputer", SimpleImputer(strategy="median")),
    ])

//anaconda3/lib/python3.7/site-packages/sklearn/utils/deprecation.py:66: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


In [10]:
num_pipeline.fit_transform(train_data)
num_pipeline.fit_transform(test_data)

array([[34.5   ,  0.    ,  0.    ,  7.8292],
       [47.    ,  1.    ,  0.    ,  7.    ],
       [62.    ,  0.    ,  0.    ,  9.6875],
       ...,
       [38.5   ,  0.    ,  0.    ,  7.25  ],
       [27.    ,  0.    ,  0.    ,  8.05  ],
       [27.    ,  1.    ,  1.    , 22.3583]])

In [11]:
class MostFrequentImputer(BaseEstimator, TransformerMixin):
    def fit(self, X, y=None):
        self.most_frequent_ = pd.Series([X[c].value_counts().index[0] for c in X],
                                        index=X.columns)
        return self
    def transform(self, X, y=None):
        return X.fillna(self.most_frequent_)

In [12]:
try:
    from sklearn.preprocessing import OrdinalEncoder # just to raise an ImportError if Scikit-Learn < 0.20
    from sklearn.preprocessing import OneHotEncoder
except ImportError:
    from future_encoders import OneHotEncoder # Scikit-Learn < 0.20

In [13]:
cat_pipeline = Pipeline([
        ("select_cat", DataFrameSelector(["Pclass", "Sex", "Embarked"])),
        ("imputer", MostFrequentImputer()),
        ("cat_encoder", OneHotEncoder(sparse=False)),
    ])

In [14]:
cat_pipeline.fit_transform(train_data)
cat_pipeline.fit_transform(test_data)

array([[0., 0., 1., ..., 0., 1., 0.],
       [0., 0., 1., ..., 0., 0., 1.],
       [0., 1., 0., ..., 0., 1., 0.],
       ...,
       [0., 0., 1., ..., 0., 0., 1.],
       [0., 0., 1., ..., 0., 0., 1.],
       [0., 0., 1., ..., 1., 0., 0.]])

In [15]:
from sklearn.pipeline import FeatureUnion
preprocess_pipeline = FeatureUnion(transformer_list=[
        ("num_pipeline", num_pipeline),
        ("cat_pipeline", cat_pipeline),
    ])

In [20]:
Y_train = train_data['Survived']
X_train_nosurvive = train_data.drop(['Survived'], axis=1)
X_train = preprocess_pipeline.fit_transform(X_train_nosurvive)

X_test = preprocess_pipeline.fit_transform(test_data)

In [21]:
# Tried RandomForest Classifier, Decision Tree Classifier, SVM, Logistic Regression, and GridSearchCV on RF, and DT 
# Random Forest was the best so I removed the others for simplicity


In [22]:
from sklearn.ensemble import RandomForestClassifier

forest_clf = RandomForestClassifier(n_estimators=100, random_state=42)

In [23]:
from sklearn.model_selection import cross_val_score
cross_val_score(forest_clf, X_train, Y_train, cv=10, scoring="accuracy")

array([0.74444444, 0.8       , 0.76404494, 0.82022472, 0.88764045,
       0.83146067, 0.83146067, 0.7752809 , 0.84269663, 0.85227273])

In [27]:
# 88.7% looks pretty good, lets try gridsearch cv
from sklearn.model_selection import GridSearchCV
param_grid = [
    # try 12 (3×4) combinations of hyperparameters
    {'max_depth':[1, 2, 3, 4],'n_estimators':[20, 25, 30, 35], 'min_samples_split':[20, 30, 40, 50], 'min_samples_leaf':[8, 9]} 
  ]

grid_search = GridSearchCV(forest_clf, param_grid, cv=10,
                           scoring='accuracy',
                           return_train_score=True)
# do it at your place....
grid_search.fit(X_train, Y_train)

GridSearchCV(cv=10, error_score='raise-deprecating',
             estimator=RandomForestClassifier(bootstrap=True, class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features='auto',
                                              max_leaf_nodes=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              n_estimators=100, n_jobs=None,
                                              oob_score=False, random_state=42,
                                              verbose=0, warm_start=False),
             iid='warn', n_jobs=None,
             param_grid=[{'m

In [28]:
print(grid_search.best_params_)

print(grid_search.param_grid)


{'max_depth': 3, 'min_samples_leaf': 8, 'min_samples_split': 30, 'n_estimators': 35}
[{'max_depth': [1, 2, 3, 4], 'n_estimators': [20, 25, 30, 35], 'min_samples_split': [20, 30, 40, 50], 'min_samples_leaf': [8, 9]}]


In [29]:
import numpy as np

cvres = grid_search.cv_results_
for mean_score, params in zip(cvres["mean_test_score"], cvres["params"]):
    print(mean_score, params)

0.7732884399551067 {'max_depth': 1, 'min_samples_leaf': 8, 'min_samples_split': 20, 'n_estimators': 20}
0.7822671156004489 {'max_depth': 1, 'min_samples_leaf': 8, 'min_samples_split': 20, 'n_estimators': 25}
0.7789001122334456 {'max_depth': 1, 'min_samples_leaf': 8, 'min_samples_split': 20, 'n_estimators': 30}
0.7598204264870931 {'max_depth': 1, 'min_samples_leaf': 8, 'min_samples_split': 20, 'n_estimators': 35}
0.7732884399551067 {'max_depth': 1, 'min_samples_leaf': 8, 'min_samples_split': 30, 'n_estimators': 20}
0.7822671156004489 {'max_depth': 1, 'min_samples_leaf': 8, 'min_samples_split': 30, 'n_estimators': 25}
0.7789001122334456 {'max_depth': 1, 'min_samples_leaf': 8, 'min_samples_split': 30, 'n_estimators': 30}
0.7598204264870931 {'max_depth': 1, 'min_samples_leaf': 8, 'min_samples_split': 30, 'n_estimators': 35}
0.7732884399551067 {'max_depth': 1, 'min_samples_leaf': 8, 'min_samples_split': 40, 'n_estimators': 20}
0.7822671156004489 {'max_depth': 1, 'min_samples_leaf': 8, 'min_

In [31]:
# Test on kaggle test set ground truth 
from sklearn.metrics import accuracy_score

final_model = grid_search.best_estimator_

test_predictions = final_model.predict(X_test)
accuracy_score(test_predictions, gtruth_just_outcomes)

0.7894736842105263

In [32]:
# Create dataframe for submission

HW4sub = pd.DataFrame({'PassengerId':test_data.PassengerId, 'Survived':test_predictions}).set_index('PassengerId')

In [33]:
HW4sub.head()

Survived
PassengerId          
892                 0
893                 0
894                 0
895                 0
896                 1

In [41]:
# Save as CSV file

pd.DataFrame({'PassengerId':test_data.PassengerId, 'Survived':test_predictions}).set_index('PassengerId').to_csv('TitanicSubHW4a.csv')